### ISSUE TITLE
I can't start a tutorial

### ISSUE THREAD

**Issue by kfern** [Fiware/tutorials.PEP-Proxy#17]
Hi!

I can't start the https://fiware-tutorials.readthedocs.io/en/latest/pep-proxy.html tutorial.

$ docker -v
**Docker version 20.10.7, build f0df350**
$ docker-compose -v
**docker-compose version 1.24.0, build 0aa59064**
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	**Ubuntu 21.10**
Release:	21.10
Codename:	impish

**./services start**
Stopping running containers
unknown shorthand flag: 'f' in -f

**./services start legacy**
Stopping running containers
WARNING: The host variable is not set. Defaulting to a blank string.
ERROR: Version in "./docker-compose/southport.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**docker-compose -f docker-compose/southport.yml config**
WARNING: The host variable is not set. Defaulting to a blank string.
ERROR: Version in "./docker-compose/southport.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Can I do something?

**Comment by jason-fox** [comment]
You have a very outdated version of `docker-compose`, so the obvious first step would be to [upgrade Docker](https://docs.docker.com/engine/install/ubuntu/). The [prerequisites](https://fiware-tutorials.readthedocs.io/en/latest/#prerequisites) page states use _"Docker Compose 1.29 or higher"_ - docker-compose 1.24  is having difficulty with understanding `version: "3.8"` in the [southport.yaml](https://github.com/FIWARE/tutorials.PEP-Proxy/blob/master/docker-compose/southport.yml#L19). Just to get it working you could reduce that to a lower number like `"3.3"` as suggested and see if that works for you - the `docker-compose.yml` files are not necessarily using 3.8 features, so that may work.

**Comment by kfern** [comment]
Thanks @jason-fox

I have resolved this issue by upgrading docker-compose to 1.29.2

I copied the linux command but didn't check it

![image](https://user-images.githubusercontent.com/1898891/179788621-cd2daf92-7103-4e5b-910f-f1d0dc0af327.png)
